def registry = 'https://satishk.jfrog.io'
def imageName = 'satishk.jfrog.io/satish-docker-local/sample_app'
def version   = '2.1.2'
pipeline {
    agent { label 'maven' }

    tools {
        maven 'maven-3.9.12'
    }

    stages {

        stage('Build') {
            steps {
                 dir('Project-2') {
                    sh 'mvn clean package -DskipTests'
                                 }
                    }
                        }

        stage('Test') {
             steps {
                dir('Project-2') {
                            sh 'mvn test'
                                 }
                    }
        }

    }
}
